#!/usr/bin/env node
/* Language Bridge — Spanish review worklist generator.
 * Walks every activity record and the UI locale, pulls out each English↔Spanish
 * pair, and writes docs/SPANISH_REVIEW.md grouped by activity so a bilingual
 * reviewer can check the whole surface fast. Also flags any localized string
 * that has English but NO Spanish yet.
 *
 * Run: node scripts/spanish-review.js   (or: npm run review:es)
 */
"use strict";
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const readJson = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), "utf8"));

// A "localized" object is one with a string `en` key (es may or may not exist).
function isLocalized(o) { return o && typeof o === "object" && typeof o.en === "string"; }

// Recursively collect { path, en, es } from an activity, with readable paths.
function collect(node, trail, out) {
  if (Array.isArray(node)) {
    node.forEach((v, i) => collect(v, trail.concat("#" + (i + 1)), out));
    return;
  }
  if (node && typeof node === "object") {
    if (isLocalized(node)) {
      out.push({ path: trail.join(" › "), en: node.en, es: typeof node.es === "string" ? node.es : null });
      // don't descend into a localized leaf's language keys
      return;
    }
    Object.keys(node).forEach((k) => {
      // skip bookkeeping keys that aren't reviewer-facing
      if (["id", "answer", "module", "gradeBand", "grades", "duration", "subjects",
           "interactionType", "targetLanguage", "supportedHomeLanguages", "languagePair",
           "created", "updated", "status", "ace", "clear", "udl", "strategies",
           "standards", "printables", "materials", "image", "targetWord", "correct"].includes(k)) {
        // still descend into items/choices/feedback/categories/support even though some keys above are skipped
        if (["items", "choices", "feedback", "categories", "support"].includes(k)) collect(node[k], trail.concat(k), out);
        return;
      }
      collect(node[k], trail.concat(k), out);
    });
  }
}

let md = "# Spanish Review Worklist\n\n";
md += "_Generated by `scripts/spanish-review.js`. Review each Spanish string against its English source; ";
md += "edit the `es` value in the module `data.json` (or `data/locales/es.json`) where needed. ";
md += "Rows flagged **⚠ NO SPANISH** have English only._\n\n";

let total = 0, missing = 0;

// ---- Activities ----
const modules = ["cognate-detective", "academic-language-lab", "newcomer-navigator"];
modules.forEach((m) => {
  const store = readJson(`modules/${m}/data.json`);
  md += `\n## Module: ${m}\n`;
  (store.activities || []).forEach((a) => {
    const rows = [];
    collect(a, [], rows);
    const title = (a.title && a.title.en) || a.id;
    md += `\n### ${title}  \`${a.id}\` — ${rows.length} strings\n\n`;
    md += "| Field | English | Spanish |\n|---|---|---|\n";
    rows.forEach((r) => {
      total++;
      const en = r.en.replace(/\|/g, "\\|").replace(/\n/g, " ");
      const es = r.es == null ? "**⚠ NO SPANISH**" : r.es.replace(/\|/g, "\\|").replace(/\n/g, " ");
      if (r.es == null) missing++;
      md += `| ${r.path} | ${en} | ${es} |\n`;
    });
  });
});

// ---- UI locale strings ----
const en = readJson("data/locales/en.json").strings;
const es = readJson("data/locales/es.json").strings;
md += `\n## UI strings (data/locales)\n\n`;
md += "| Key | Status | English | Spanish |\n|---|---|---|---|\n";
Object.keys(en).forEach((k) => {
  total++;
  const e = en[k].text.replace(/\|/g, "\\|");
  const sEntry = es[k];
  const s = sEntry ? sEntry.text.replace(/\|/g, "\\|") : "**⚠ NO SPANISH**";
  if (!sEntry) missing++;
  const st = sEntry ? sEntry.status : "—";
  md += `| \`${k}\` | ${st} | ${e} | ${s} |\n`;
});

md = md.replace("_Generated by", `**${total} strings total; ${missing} missing Spanish.**\n\n_Generated by`);

fs.writeFileSync(path.join(ROOT, "docs/SPANISH_REVIEW.md"), md);
console.log(`spanish-review: wrote docs/SPANISH_REVIEW.md — ${total} strings, ${missing} missing Spanish.`);
